CREATE TABLE reminders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reminder_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    completed     BOOLEAN                                 NOT NULL,
    post_id       BIGINT,
    CONSTRAINT pk_reminders PRIMARY KEY (id)
);

ALTER TABLE reminders
    ADD CONSTRAINT uc_reminders_post UNIQUE (post_id);

ALTER TABLE reminders
    ADD CONSTRAINT FK_REMINDERS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);