CREATE TABLE device_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_token VARCHAR(255),
    user_id      BIGINT,
    CONSTRAINT pk_devicetokens PRIMARY KEY (id)
);

ALTER TABLE device_tokens
    ADD CONSTRAINT FK_DEVICETOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);