CREATE TABLE reminders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reminder_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    message       VARCHAR(255),
    is_done       BOOLEAN                                 NOT NULL,
    user_id       BIGINT,
    CONSTRAINT pk_reminders PRIMARY KEY (id)
);

ALTER TABLE reminders
    ADD CONSTRAINT FK_REMINDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);